name: breaking_bapp
description: Sample app for the Infinite Scroll Pagination package.
publish_to: none
version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cached_network_image: ^2.3.2+1
  flutter:
    sdk: flutter
  http: 0.12.0+4
  infinite_scroll_pagination:
    path: ../
  rxdart: ^0.24.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true